version: '3.8'

services:
  valkey:
    image: valkey/valkey:latest
    restart: always
    command: valkey-server --appendonly yes
    volumes:
      - valkey_data:/data

  user-service:
    image: ghcr.io/zain4391/user-service:latest
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN}
      - BCRYPT_ROUNDS=${BCRYPT_ROUNDS}

  product-service:
    image: ghcr.io/zain4391/product-service:latest
    restart: always
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - REDIS_HOST=valkey
    depends_on:
      - valkey

  order-service:
    image: ghcr.io/zain4391/order-service:latest
    restart: always
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PORT=3003
      - REDIS_HOST=valkey
    depends_on:
      - valkey

  payment-service:
    image: ghcr.io/zain4391/payment-service:latest
    restart: always
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - PORT=3004
      - REDIS_HOST=valkey
    depends_on:
      - valkey

volumes:
  valkey_data: